---
name: idr0085-walsh-mfhrem/experimentA
version: 1

defaults:
  include: no
  type: string
  includeclient: yes
  visible: yes
  omitempty: yes

columns:

  - name: Characteristics [Organism Part]
    clientname: Organism Part
    include: yes

  - name: Experimental Condition [Wavelength]
    clientname: Wavelength
    include: yes

  - name: Comment [Image]
    clientname: Image Comment
    include: yes

  - name: Channels
    clientname: Channels
    include: yes

  - name: Comment [Channels]
    clientname: Channels Comment
    include: yes


  ######################################################################
  # mapr groups
  ######################################################################

  - group:
      namespace: openmicroscopy.org/mapr/organism
      columns:
        - name: Characteristics [Organism]
          clientname: Organism
          include: yes


advanced:
  ignore_missing_primary_key: yes
  primary_group_keys:
    - namespace: openmicroscopy.org/mapr/organism
      keys:
        - Organism
